<?php

namespace Database\Seeders;

use App\Models\ProductTemplate;
use Illuminate\Database\Seeder;

class ProductTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $consumables = [
            ['name' => 'Ballpoint Pen (Blue)', 'category' => 'Writing & Drawing'],
            ['name' => 'Ballpoint Pen (Black)', 'category' => 'Writing & Drawing'],
            ['name' => 'Ballpoint Pen (Red)', 'category' => 'Writing & Drawing'],
            ['name' => 'Ballpoint Pen (Green)', 'category' => 'Writing & Drawing'],
            ['name' => 'Rollerball Pen', 'category' => 'Writing & Drawing'],
            ['name' => 'Gel Pen', 'category' => 'Writing & Drawing'],
            ['name' => 'Fountain Pen Ink Cartridge', 'category' => 'Writing & Drawing'],
            ['name' => 'Pencil (HB)', 'category' => 'Writing & Drawing'],
            ['name' => 'Pencil (2B)', 'category' => 'Writing & Drawing'],
            ['name' => 'Mechanical Pencil', 'category' => 'Writing & Drawing'],
            ['name' => 'Pencil Lead Refill', 'category' => 'Writing & Drawing'],
            ['name' => 'Eraser', 'category' => 'Writing & Drawing'],
            ['name' => 'Highlighter (Yellow)', 'category' => 'Writing & Drawing'],
            ['name' => 'Highlighter (Green)', 'category' => 'Writing & Drawing'],
            ['name' => 'Highlighter (Pink)', 'category' => 'Writing & Drawing'],
            ['name' => 'Permanent Marker', 'category' => 'Writing & Drawing'],
            ['name' => 'Dry Erase Marker', 'category' => 'Writing & Drawing'],
            ['name' => 'Whiteboard Marker Set', 'category' => 'Writing & Drawing'],
            ['name' => 'Correction Tape', 'category' => 'Writing & Drawing'],
            ['name' => 'Liquid Correction Fluid', 'category' => 'Writing & Drawing'],
            ['name' => 'Stapler', 'category' => 'Fastening'],
            ['name' => 'Staples (Box)', 'category' => 'Fastening'],
            ['name' => 'Staple Remover', 'category' => 'Fastening'],
            ['name' => 'Paper Clips (Box)', 'category' => 'Fastening'],
            ['name' => 'Binder Clips (Assorted)', 'category' => 'Fastening'],
            ['name' => 'Push Pins', 'category' => 'Fastening'],
            ['name' => 'Rubber Bands (Pack)', 'category' => 'Fastening'],
            ['name' => 'Sticky Notes (Pad)', 'category' => 'Paper & Pads'],
            ['name' => 'Sticky Notes (Assorted Colors)', 'category' => 'Paper & Pads'],
            ['name' => 'Copy Paper (Ream)', 'category' => 'Paper & Pads'],
            ['name' => 'Recycled Copy Paper (Ream)', 'category' => 'Paper & Pads'],
            ['name' => 'Colored Paper (Pack)', 'category' => 'Paper & Pads'],
            ['name' => 'Notepad (Lined)', 'category' => 'Paper & Pads'],
            ['name' => 'Notepad (Grid)', 'category' => 'Paper & Pads'],
            ['name' => 'Legal Pad', 'category' => 'Paper & Pads'],
            ['name' => 'Graph Paper Pad', 'category' => 'Paper & Pads'],
            ['name' => 'Memo Cube', 'category' => 'Paper & Pads'],
            ['name' => 'Envelope (Letter Size)', 'category' => 'Paper & Pads'],
            ['name' => 'Envelope (A4)', 'category' => 'Paper & Pads'],
            ['name' => 'Manila Folder', 'category' => 'Filing & Storage'],
            ['name' => 'Hanging Folder', 'category' => 'Filing & Storage'],
            ['name' => 'File Folder (Assorted)', 'category' => 'Filing & Storage'],
            ['name' => 'Expandable Folder', 'category' => 'Filing & Storage'],
            ['name' => 'Document Sleeve', 'category' => 'Filing & Storage'],
            ['name' => 'Sheet Protector', 'category' => 'Filing & Storage'],
            ['name' => 'Binders (1 inch)', 'category' => 'Filing & Storage'],
            ['name' => 'Binders (2 inch)', 'category' => 'Filing & Storage'],
            ['name' => 'Binders (3 inch)', 'category' => 'Filing & Storage'],
            ['name' => 'Index Dividers', 'category' => 'Filing & Storage'],
            ['name' => 'Transparent Tape Roll', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Double-Sided Tape', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Masking Tape', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Duct Tape', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Glue Stick', 'category' => 'Adhesives & Tapes'],
            ['name' => 'White Glue (Bottle)', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Glue Dots', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Tape Dispenser', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Scissors', 'category' => 'Desk Tools'],
            ['name' => 'Letter Opener', 'category' => 'Desk Tools'],
            ['name' => 'Hole Punch (2-Hole)', 'category' => 'Desk Tools'],
            ['name' => 'Hole Punch (3-Hole)', 'category' => 'Desk Tools'],
            ['name' => 'Ruler (12 inch)', 'category' => 'Desk Tools'],
            ['name' => 'Ruler (Metric)', 'category' => 'Desk Tools'],
            ['name' => 'Calculator (Basic)', 'category' => 'Desk Tools'],
            ['name' => 'Desk Organizer Tray', 'category' => 'Desk Organizers'],
            ['name' => 'Pen Holder', 'category' => 'Desk Organizers'],
            ['name' => 'In/Out Tray', 'category' => 'Desk Organizers'],
            ['name' => 'Business Card Holder', 'category' => 'Desk Organizers'],
            ['name' => 'Desk Caddy', 'category' => 'Desk Organizers'],
            ['name' => 'Drawer Organizer', 'category' => 'Desk Organizers'],
            ['name' => 'Wastebasket', 'category' => 'Desk Organizers'],
            ['name' => 'Recycling Bin', 'category' => 'Desk Organizers'],
            ['name' => 'Laminating Pouches', 'category' => 'Presentation'],
            ['name' => 'Presentation Folder', 'category' => 'Presentation'],
            ['name' => 'Name Badge Holder', 'category' => 'Presentation'],
            ['name' => 'Lanyard', 'category' => 'Presentation'],
            ['name' => 'ID Badge Clip', 'category' => 'Presentation'],
            ['name' => 'Toner Cartridge (Black)', 'category' => 'Printing Supplies'],
            ['name' => 'Toner Cartridge (Cyan)', 'category' => 'Printing Supplies'],
            ['name' => 'Toner Cartridge (Magenta)', 'category' => 'Printing Supplies'],
            ['name' => 'Toner Cartridge (Yellow)', 'category' => 'Printing Supplies'],
            ['name' => 'Ink Cartridge (Black)', 'category' => 'Printing Supplies'],
            ['name' => 'Ink Cartridge (Color)', 'category' => 'Printing Supplies'],
            ['name' => 'Inkjet Photo Paper', 'category' => 'Printing Supplies'],
            ['name' => 'Labels (Sheet)', 'category' => 'Printing Supplies'],
            ['name' => 'Address Labels', 'category' => 'Printing Supplies'],
            ['name' => 'CD/DVD Sleeve', 'category' => 'Media & Discs'],
            ['name' => 'USB Flash Drive (8GB)', 'category' => 'Media & Discs'],
            ['name' => 'USB Flash Drive (16GB)', 'category' => 'Media & Discs'],
            ['name' => 'USB Flash Drive (32GB)', 'category' => 'Media & Discs'],
            ['name' => 'CD-R (Spindle)', 'category' => 'Media & Discs'],
            ['name' => 'DVD-R (Spindle)', 'category' => 'Media & Discs'],
            ['name' => 'Cleaning Wipes (Monitor)', 'category' => 'Cleaning'],
            ['name' => 'Cleaning Wipes (General)', 'category' => 'Cleaning'],
            ['name' => 'Dusting Spray', 'category' => 'Cleaning'],
            ['name' => 'Hand Sanitizer', 'category' => 'Cleaning'],
            ['name' => 'Tissue Box', 'category' => 'Cleaning'],
            ['name' => 'Paper Towels', 'category' => 'Cleaning'],
            ['name' => 'Sponge', 'category' => 'Cleaning'],
            ['name' => 'Trash Bags', 'category' => 'Cleaning'],
            ['name' => 'Disinfectant Spray', 'category' => 'Cleaning'],
            ['name' => 'Coffee (Ground)', 'category' => 'Break Room'],
            ['name' => 'Coffee (Whole Bean)', 'category' => 'Break Room'],
            ['name' => 'Tea Bags (Assorted)', 'category' => 'Break Room'],
            ['name' => 'Sugar Packets', 'category' => 'Break Room'],
            ['name' => 'Creamer (Powder)', 'category' => 'Break Room'],
            ['name' => 'Disposable Cups', 'category' => 'Break Room'],
            ['name' => 'Paper Plates', 'category' => 'Break Room'],
            ['name' => 'Plastic Utensils', 'category' => 'Break Room'],
            ['name' => 'Napkins', 'category' => 'Break Room'],
            ['name' => 'Dish Soap', 'category' => 'Break Room'],
            ['name' => 'Sponge (Kitchen)', 'category' => 'Break Room'],
            ['name' => 'First Aid Kit (Refill)', 'category' => 'Safety'],
            ['name' => 'Bandages', 'category' => 'Safety'],
            ['name' => 'Antiseptic Wipes', 'category' => 'Safety'],
            ['name' => 'Pain Reliever', 'category' => 'Safety'],
            ['name' => 'Safety Goggles', 'category' => 'Safety'],
            ['name' => 'Disposable Gloves', 'category' => 'Safety'],
            ['name' => 'Face Mask (Box)', 'category' => 'Safety'],
            ['name' => 'Batteries (AA)', 'category' => 'Electrical'],
            ['name' => 'Batteries (AAA)', 'category' => 'Electrical'],
            ['name' => 'Batteries (9V)', 'category' => 'Electrical'],
            ['name' => 'Power Strip', 'category' => 'Electrical'],
            ['name' => 'Extension Cord', 'category' => 'Electrical'],
            ['name' => 'Cable Ties', 'category' => 'Electrical'],
            ['name' => 'Velcro Cable Wrap', 'category' => 'Electrical'],
            ['name' => 'Screen Cleaner Kit', 'category' => 'IT Consumables'],
            ['name' => 'Keyboard Dust Cleaner', 'category' => 'IT Consumables'],
            ['name' => 'Compressed Air Duster', 'category' => 'IT Consumables'],
            ['name' => 'Mouse Pad', 'category' => 'IT Consumables'],
            ['name' => 'Wrist Rest', 'category' => 'IT Consumables'],
            ['name' => 'Laptop Sleeve', 'category' => 'IT Consumables'],
            ['name' => 'Phone Stand', 'category' => 'IT Consumables'],
            ['name' => 'Tablet Stand', 'category' => 'IT Consumables'],
            ['name' => 'HDMI Cable', 'category' => 'Cables'],
            ['name' => 'USB Cable (A to B)', 'category' => 'Cables'],
            ['name' => 'USB Cable (Type-C)', 'category' => 'Cables'],
            ['name' => 'Ethernet Cable', 'category' => 'Cables'],
            ['name' => 'VGA Cable', 'category' => 'Cables'],
            ['name' => 'DisplayPort Cable', 'category' => 'Cables'],
            ['name' => 'Adapter (HDMI to VGA)', 'category' => 'Cables'],
            ['name' => 'USB Hub', 'category' => 'Cables'],
            ['name' => 'Sticky Tack', 'category' => 'Adhesives & Tapes'],
            ['name' => 'Bulldog Clip', 'category' => 'Fastening'],
            ['name' => 'Clipboard', 'category' => 'Desk Tools'],
            ['name' => 'Bookmark', 'category' => 'Writing & Drawing'],
            ['name' => 'Stamp Pad', 'category' => 'Desk Tools'],
            ['name' => 'Rubber Stamp', 'category' => 'Desk Tools'],
            ['name' => 'Date Stamp', 'category' => 'Desk Tools'],
            ['name' => 'Shredder Oil', 'category' => 'Office Machines'],
            ['name' => 'Shredder Bags', 'category' => 'Office Machines'],
            ['name' => 'Projector Lamp', 'category' => 'Presentation'],
            ['name' => 'Whiteboard Eraser', 'category' => 'Presentation'],
            ['name' => 'Flip Chart Pad', 'category' => 'Presentation'],
            ['name' => 'Flip Chart Markers', 'category' => 'Presentation'],
            ['name' => 'Name Plate', 'category' => 'Desk Organizers'],
            ['name' => 'Desk Calendar', 'category' => 'Desk Organizers'],
            ['name' => 'Wall Calendar', 'category' => 'Desk Organizers'],
            ['name' => 'Planner Refill', 'category' => 'Paper & Pads'],
            ['name' => 'Day Planner', 'category' => 'Paper & Pads'],
            ['name' => 'Portfolio Folder', 'category' => 'Filing & Storage'],
            ['name' => 'Report Cover', 'category' => 'Filing & Storage'],
            ['name' => 'Binding Comb', 'category' => 'Filing & Storage'],
            ['name' => 'Spine Label', 'category' => 'Filing & Storage'],
            ['name' => 'Tab Dividers', 'category' => 'Filing & Storage'],
            ['name' => 'Card Stock (Pack)', 'category' => 'Paper & Pads'],
            ['name' => 'Bulk Envelopes', 'category' => 'Paper & Pads'],
            ['name' => 'Shipping Labels', 'category' => 'Printing Supplies'],
            ['name' => 'Barcode Labels', 'category' => 'Printing Supplies'],
            ['name' => 'Security Envelope', 'category' => 'Paper & Pads'],
            ['name' => 'Padded Envelope', 'category' => 'Paper & Pads'],
            ['name' => 'Bubble Wrap', 'category' => 'Shipping'],
            ['name' => 'Packing Tape', 'category' => 'Shipping'],
            ['name' => 'Box Sealing Tape', 'category' => 'Shipping'],
            ['name' => 'Shipping Box (Small)', 'category' => 'Shipping'],
            ['name' => 'Shipping Box (Medium)', 'category' => 'Shipping'],
            ['name' => 'Shipping Box (Large)', 'category' => 'Shipping'],
            ['name' => 'Filler Paper', 'category' => 'Paper & Pads'],
            ['name' => 'Graph Paper', 'category' => 'Paper & Pads'],
            ['name' => 'Tracing Paper', 'category' => 'Paper & Pads'],
            ['name' => 'Carbon Paper', 'category' => 'Paper & Pads'],
            ['name' => 'Chalk', 'category' => 'Writing & Drawing'],
            ['name' => 'Crayons', 'category' => 'Writing & Drawing'],
            ['name' => 'Markers (Set)', 'category' => 'Writing & Drawing'],
            ['name' => 'Colored Pencils', 'category' => 'Writing & Drawing'],
            ['name' => 'Sharpener', 'category' => 'Writing & Drawing'],
            ['name' => 'Compass (Drawing)', 'category' => 'Writing & Drawing'],
            ['name' => 'Protractor', 'category' => 'Writing & Drawing'],
            ['name' => 'Sticky Flags', 'category' => 'Filing & Storage'],
            ['name' => 'Page Markers', 'category' => 'Filing & Storage'],
            ['name' => 'Book Ends', 'category' => 'Desk Organizers'],
            ['name' => 'Magazine File', 'category' => 'Filing & Storage'],
            ['name' => 'Document Tray', 'category' => 'Desk Organizers'],
            ['name' => 'Filing Tray', 'category' => 'Desk Organizers'],
            ['name' => 'Letter Tray', 'category' => 'Desk Organizers'],
            ['name' => 'Desk Lamp Bulb', 'category' => 'Electrical'],
            ['name' => 'Fluorescent Tube', 'category' => 'Electrical'],
            ['name' => 'LED Bulb', 'category' => 'Electrical'],
            ['name' => 'Pencil Case', 'category' => 'Desk Organizers'],
            ['name' => 'Desk Mat', 'category' => 'Desk Organizers'],
            ['name' => 'Coaster Set', 'category' => 'Break Room'],
            ['name' => 'Water Bottle', 'category' => 'Break Room'],
            ['name' => 'Desk Fan', 'category' => 'Electrical'],
            ['name' => 'Space Heater', 'category' => 'Electrical'],
            ['name' => 'Air Purifier Filter', 'category' => 'Cleaning'],
            ['name' => 'Whiteboard Cleaner', 'category' => 'Cleaning'],
            ['name' => 'Printer Cleaning Kit', 'category' => 'IT Consumables'],
            ['name' => 'Keyboard Cover', 'category' => 'IT Consumables'],
            ['name' => 'Laptop Lock', 'category' => 'Security'],
            ['name' => 'Cable Lock', 'category' => 'Security'],
            ['name' => 'Visitor Log Book', 'category' => 'Filing & Storage'],
            ['name' => 'Receipt Book', 'category' => 'Paper & Pads'],
            ['name' => 'Invoice Book', 'category' => 'Paper & Pads'],
            ['name' => 'Time Sheet Pad', 'category' => 'Paper & Pads'],
            ['name' => 'Expense Form Pad', 'category' => 'Paper & Pads'],
            ['name' => 'Business Card Stock', 'category' => 'Printing Supplies'],
            ['name' => 'Brochure Paper', 'category' => 'Printing Supplies'],
            ['name' => 'Certificate Paper', 'category' => 'Printing Supplies'],
            ['name' => 'Transfer Paper', 'category' => 'Printing Supplies'],
            ['name' => 'Greeting Card (Blank)', 'category' => 'Paper & Pads'],
            ['name' => 'Thank You Card', 'category' => 'Paper & Pads'],
            ['name' => 'Invitation Envelope', 'category' => 'Paper & Pads'],
            ['name' => 'Gift Wrap', 'category' => 'Shipping'],
            ['name' => 'Fragile Stickers', 'category' => 'Shipping'],
            ['name' => 'Return Address Label', 'category' => 'Printing Supplies'],
            ['name' => 'Folder with Clasp', 'category' => 'Filing & Storage'],
            ['name' => 'Pocket Folder', 'category' => 'Filing & Storage'],
        ];

        $capital = [
            ['name' => 'Desktop Computer', 'category' => 'Computers'],
            ['name' => 'Laptop Computer', 'category' => 'Computers'],
            ['name' => 'All-in-One PC', 'category' => 'Computers'],
            ['name' => 'Workstation', 'category' => 'Computers'],
            ['name' => 'Server', 'category' => 'Computers'],
            ['name' => 'Monitor (19 inch)', 'category' => 'Monitors & Displays'],
            ['name' => 'Monitor (22 inch)', 'category' => 'Monitors & Displays'],
            ['name' => 'Monitor (24 inch)', 'category' => 'Monitors & Displays'],
            ['name' => 'Monitor (27 inch)', 'category' => 'Monitors & Displays'],
            ['name' => 'Monitor (32 inch)', 'category' => 'Monitors & Displays'],
            ['name' => 'Ultrawide Monitor', 'category' => 'Monitors & Displays'],
            ['name' => '4K Monitor', 'category' => 'Monitors & Displays'],
            ['name' => 'Docking Station', 'category' => 'Computers'],
            ['name' => 'Keyboard (Wired)', 'category' => 'Peripherals'],
            ['name' => 'Keyboard (Wireless)', 'category' => 'Peripherals'],
            ['name' => 'Keyboard (Mechanical)', 'category' => 'Peripherals'],
            ['name' => 'Mouse (Wired)', 'category' => 'Peripherals'],
            ['name' => 'Mouse (Wireless)', 'category' => 'Peripherals'],
            ['name' => 'Mouse (Ergonomic)', 'category' => 'Peripherals'],
            ['name' => 'Webcam', 'category' => 'Peripherals'],
            ['name' => 'Headset (Wired)', 'category' => 'Peripherals'],
            ['name' => 'Headset (Wireless)', 'category' => 'Peripherals'],
            ['name' => 'USB Speaker', 'category' => 'Peripherals'],
            ['name' => 'Microphone', 'category' => 'Peripherals'],
            ['name' => 'Laptop Stand', 'category' => 'Ergonomics'],
            ['name' => 'Monitor Arm', 'category' => 'Ergonomics'],
            ['name' => 'Standing Desk', 'category' => 'Furniture'],
            ['name' => 'Sit-Stand Desk Converter', 'category' => 'Furniture'],
            ['name' => 'Office Chair', 'category' => 'Furniture'],
            ['name' => 'Ergonomic Chair', 'category' => 'Furniture'],
            ['name' => 'Guest Chair', 'category' => 'Furniture'],
            ['name' => 'Conference Chair', 'category' => 'Furniture'],
            ['name' => 'Desk', 'category' => 'Furniture'],
            ['name' => 'Conference Table', 'category' => 'Furniture'],
            ['name' => 'Meeting Table', 'category' => 'Furniture'],
            ['name' => 'Filing Cabinet (2-Drawer)', 'category' => 'Furniture'],
            ['name' => 'Filing Cabinet (4-Drawer)', 'category' => 'Furniture'],
            ['name' => 'Lateral File Cabinet', 'category' => 'Furniture'],
            ['name' => 'Bookcase', 'category' => 'Furniture'],
            ['name' => 'Storage Cabinet', 'category' => 'Furniture'],
            ['name' => 'Printer (Desktop)', 'category' => 'Office Machines'],
            ['name' => 'Printer (Multifunction)', 'category' => 'Office Machines'],
            ['name' => 'Laser Printer', 'category' => 'Office Machines'],
            ['name' => 'Inkjet Printer', 'category' => 'Office Machines'],
            ['name' => 'Scanner (Flatbed)', 'category' => 'Office Machines'],
            ['name' => 'Document Scanner', 'category' => 'Office Machines'],
            ['name' => 'Shredder', 'category' => 'Office Machines'],
            ['name' => 'Label Maker', 'category' => 'Office Machines'],
            ['name' => 'Laminator', 'category' => 'Office Machines'],
            ['name' => 'Binding Machine', 'category' => 'Office Machines'],
            ['name' => 'Projector', 'category' => 'Presentation'],
            ['name' => 'Projector Screen', 'category' => 'Presentation'],
            ['name' => 'Interactive Whiteboard', 'category' => 'Presentation'],
            ['name' => 'Whiteboard (Wall Mount)', 'category' => 'Presentation'],
            ['name' => 'Whiteboard (Mobile)', 'category' => 'Presentation'],
            ['name' => 'Flip Chart Stand', 'category' => 'Presentation'],
            ['name' => 'Presentation Remote', 'category' => 'Presentation'],
            ['name' => 'Video Conferencing System', 'category' => 'Communication'],
            ['name' => 'Conference Phone', 'category' => 'Communication'],
            ['name' => 'IP Phone', 'category' => 'Communication'],
            ['name' => 'Cordless Phone', 'category' => 'Communication'],
            ['name' => 'Fax Machine', 'category' => 'Communication'],
            ['name' => 'Router', 'category' => 'Networking'],
            ['name' => 'Network Switch', 'category' => 'Networking'],
            ['name' => 'Wireless Access Point', 'category' => 'Networking'],
            ['name' => 'Network Cabinet', 'category' => 'Networking'],
            ['name' => 'NAS Device', 'category' => 'Networking'],
            ['name' => 'UPS (Uninterruptible Power Supply)', 'category' => 'Electrical'],
            ['name' => 'Battery Backup', 'category' => 'Electrical'],
            ['name' => 'Surge Protector', 'category' => 'Electrical'],
            ['name' => 'Desk Lamp', 'category' => 'Furniture'],
            ['name' => 'Task Lamp', 'category' => 'Furniture'],
            ['name' => 'Floor Lamp', 'category' => 'Furniture'],
            ['name' => 'Safe (Office)', 'category' => 'Security'],
            ['name' => 'Fireproof Cabinet', 'category' => 'Security'],
            ['name' => 'Locking Cabinet', 'category' => 'Security'],
            ['name' => 'Coat Rack', 'category' => 'Furniture'],
            ['name' => 'Reception Desk', 'category' => 'Furniture'],
            ['name' => 'Waiting Room Bench', 'category' => 'Furniture'],
            ['name' => 'Mobile Whiteboard', 'category' => 'Presentation'],
            ['name' => 'Portable Projector', 'category' => 'Presentation'],
            ['name' => 'Document Camera', 'category' => 'Presentation'],
            ['name' => 'Tablet (iPad/Android)', 'category' => 'Computers'],
            ['name' => 'E-Reader', 'category' => 'Computers'],
            ['name' => 'Smart TV (Conference)', 'category' => 'Monitors & Displays'],
            ['name' => 'Display Board', 'category' => 'Presentation'],
            ['name' => 'Digital Signage Player', 'category' => 'Presentation'],
            ['name' => 'Barcode Scanner', 'category' => 'Office Machines'],
            ['name' => 'Card Reader', 'category' => 'Security'],
            ['name' => 'Time Clock', 'category' => 'HR Equipment'],
            ['name' => 'Calculator (Printing)', 'category' => 'Office Machines'],
            ['name' => 'Cash Register', 'category' => 'Office Machines'],
            ['name' => 'Receipt Printer', 'category' => 'Office Machines'],
            ['name' => 'Label Printer', 'category' => 'Office Machines'],
            ['name' => 'Paper Cutter', 'category' => 'Office Machines'],
            ['name' => 'Folding Machine', 'category' => 'Office Machines'],
            ['name' => 'Letter Opener (Electric)', 'category' => 'Office Machines'],
        ];

        foreach ($consumables as $item) {
            ProductTemplate::firstOrCreate(
                ['name' => $item['name'], 'type' => 'consumable'],
                ['category' => $item['category']]
            );
        }
        foreach ($capital as $item) {
            ProductTemplate::firstOrCreate(
                ['name' => $item['name'], 'type' => 'capital'],
                ['category' => $item['category']]
            );
        }
    }
}
